package com.voxly.data.local.cache

import com.voxly.core.util.PathUtils
import com.voxly.domain.model.AudioFile
import com.voxly.domain.model.AudioFormat
import com.voxly.domain.model.AudioMetadata
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Regression tests for the cross-workspace cache-collision bug fixed in v15
 * (see lesson.md #24 + #25). These tests guard the *invariant* — "path is the
 * only identity" — so a future refactor cannot silently re-introduce a
 * polymorphic or hash-derived primary key.
 *
 * The pre-fix bug: `CachedAudioFileEntity.id` was generated by three different
 * algorithms across the codebase (MediaStore `_ID`, `path.hashCode()`, etc.),
 * and after the first save it mutated from one to another. For two workspace
 * directories containing the same song at different paths, `String.hashCode()`
 * is 32-bit and collisions are statistically certain in libraries with a few
 * thousand files. SQLite's `INSERT OR REPLACE` would silently drop the older
 * row, making the other workspace's song "disappear".
 */
class CachedAudioFileIdentityTest {

    /**
     * **Invariant 1**: `AudioFile` no longer has an `id` field. The natural
     * identity of a file in the domain is its `path`. The previous `id: String`
     * was the polymorphic container that held either the MediaStore `_ID` (at
     * scan time) or `path.hashCode()` (after the first save).
     *
     * This is a compile-time-style check expressed in plain JUnit: if a future
     * refactor re-adds an `id` field to `AudioFile`, this test stops compiling
     * because `path` will no longer be the only identity-bearing parameter
     * needed to construct an `AudioFile` for the equality assertion.
     */
    @Test
    fun `AudioFile uses path as the sole identity - no id field`() {
        val file = AudioFile(
            path = "/storage/emulated/0/Music/song.mp3",
            name = "song.mp3",
            size = 1024L,
            duration = 180_000L,
            format = AudioFormat.MP3,
            bitrate = 320,
            sampleRate = 44_100,
            channels = 2,
            metadata = AudioMetadata(title = "Song", artist = "Artist")
        )

        // Two AudioFiles with the same path are structurally equal (data-class
        // equality) — path is the only identity.
        val same = AudioFile(
            path = "/storage/emulated/0/Music/song.mp3",
            name = "song.mp3",
            size = 1024L,
            duration = 180_000L,
            format = AudioFormat.MP3,
            bitrate = 320,
            sampleRate = 44_100,
            channels = 2,
            metadata = AudioMetadata(title = "Song", artist = "Artist")
        )
        assertEquals(file, same)
    }

    /**
     * **Invariant 2**: `CachedAudioFileEntity.fromAudioFile` and `toAudioFile`
     * round-trip preserves `path` exactly. The previous round-trip drifted the
     * `id` field from the MediaStore `_ID` to `path.hashCode()` on the way
     * back — this is what made the primary key unstable.
     */
    @Test
    fun `CachedAudioFileEntity roundtrip preserves path as the only identity`() {
        val original = AudioFile(
            path = "/storage/emulated/0/Music/workspaceA/song.mp3",
            name = "song.mp3",
            size = 2048L,
            duration = 240_000L,
            format = AudioFormat.FLAC,
            bitrate = 1000,
            sampleRate = 48_000,
            channels = 2,
            metadata = AudioMetadata(
                title = "Same Song",
                artist = "Same Artist",
                album = "Same Album"
            )
        )

        val entity = CachedAudioFileEntity.fromAudioFile(
            audioFile = original,
            fileLastModified = 12345L
        )

        // The entity's PK is the path itself, with NO separate `id` field.
        assertEquals(original.path, entity.path)

        val roundTripped = entity.toAudioFile()
        assertEquals(original.path, roundTripped.path)
        assertEquals(original.metadata.title, roundTripped.metadata.title)
        assertEquals(original.metadata.album, roundTripped.metadata.album)
    }

    /**
     * **Invariant 3** (regression): two paths whose `String.hashCode()` values
     * collide under the old scheme are now treated as two distinct cache rows
     * (because the new primary key is the path itself, not a 32-bit hash).
     *
     * We don't try to find real hash-colliding paths in the test (that would
     * be brittle and platform-dependent); instead we *simulate* the
     * pathological case by asserting that the round-tripped `path` strings
     * are byte-equal to the inputs, regardless of any hash-derived value.
     * This is the structural reason the bug is gone: with `path` as PK, hash
     * collision is irrelevant.
     */
    @Test
    fun `distinct paths that would hash-collide now stay distinct rows`() {
        // Construct two paths that look structurally similar — the kind that
        // historically hash-collided across long path strings. We don't need
        // them to ACTUALLY collide in this JVM (JVM hashCode() is deterministic
        // but we don't want to assert a specific 32-bit value); we only need
        // the *invariant* that each path is its own row.
        val pathA = "/storage/emulated/0/Music/workspaceA/Artist/Album/song.mp3"
        val pathB = "/storage/emulated/0/Music/workspaceB/Artist/Album/song.mp3"

        // Confirm they are distinct strings (sanity).
        assertNotEquals(pathA, pathB)

        val fileA = makeEntity(pathA)
        val fileB = makeEntity(pathB)

        // The path is the PK — two distinct paths must produce two distinct
        // primary keys, and any path-based lookup must round-trip back to the
        // same path.
        assertEquals(pathA, fileA.toAudioFile().path)
        assertEquals(pathB, fileB.toAudioFile().path)
        // And the entities themselves are not equal (different PKs).
        assertNotEquals(fileA, fileB)
    }

    /**
     * **Invariant 4**: `PathUtils.normalizeFilePath` collapses paths that
     * differ only in duplicate slashes or backslash/forward slash — so two
     * callers that pass `/foo//bar` and `/foo/bar` hit the same cache row
     * under the new path-as-PK schema. (`./` segments are NOT collapsed for
     * non-existent files, because that resolution needs the real filesystem
     * via `File.canonicalPath` — which the unit test environment cannot
     * provide. This is the documented behavior; the integration / instrumented
     * tests verify the canonical-path branch on real files.)
     */
    @Test
    fun `PathUtils normalizes equivalent path representations to one key`() {
        val canonical = "/storage/emulated/0/Music/song.mp3"
        assertEquals(canonical, PathUtils.normalizeFilePath("/storage/emulated/0/Music//song.mp3"))
        assertEquals(canonical, PathUtils.normalizeFilePath("/storage/emulated/0/Music///song.mp3"))
        assertEquals(canonical, PathUtils.normalizeFilePath("\\storage\\emulated\\0\\Music\\song.mp3"))
        // NFC: macOS HFS+ / external storage sometimes delivers NFD-encoded
        // filenames; the normalizer must canonicalize to NFC for consistent
        // cache-key equality.
        assertEquals(canonical, PathUtils.normalizeFilePath(canonical))
    }

    /**
     * **Invariant 5**: `CachedAudioFileEntity` is keyed on `path`. Inserting
     * two entities with the same `path` is a primary-key conflict that the
     * DAO's REPLACE strategy collapses into one row (the lossy `id`-hash
     * behavior is impossible because there is no hash). We verify this by
     * direct construction only — exercising the SQL constraint requires
     * running Room, which is covered by the integration tests on the
     * instrumented side.
     */
    @Test
    fun `entity primary key is path - no hash-derived id column`() {
        val a = makeEntity("/storage/song.mp3")
        val b = makeEntity("/storage/song.mp3")

        // Same path → same primary key → entities are equal under data-class
        // equality (which compares all fields, including the PK).
        assertEquals(a, b)
        // And — crucially — there is no separate `id` field that could drift
        // and silently make them unequal in the future.
        val fields = AudioFile::class.java.declaredFields.map { it.name }
        assertTrue(
            "AudioFile must not carry a polymorphic id field (lesson.md #24 + #25); got: $fields",
            "id" !in fields
        )
    }

    private fun makeEntity(path: String): CachedAudioFileEntity =
        CachedAudioFileEntity.fromAudioFile(
            audioFile = AudioFile(
                path = path,
                name = path.substringAfterLast('/'),
                size = 1024L,
                duration = 180_000L,
                format = AudioFormat.MP3,
                bitrate = 320,
                sampleRate = 44_100,
                channels = 2,
                metadata = AudioMetadata(title = "T", artist = "A", album = "Al")
            ),
            fileLastModified = 0L
        )
}
